[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.1"
  # Utiliser legacy-peer-deps pour ignorer les erreurs de dépendances
  NPM_FLAGS = "--legacy-peer-deps"
  # Désactiver la télémétrie Astro
  ASTRO_TELEMETRY_DISABLED = "1"
  # Force l'utilisation du mode statique
  ASTRO_OUTPUT = "static"

[[redirects]]
  from = "/career/*"
  to = "/career/#:splat"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200