[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--legacy-peer-deps --force"
  ASTRO_TELEMETRY_DISABLED = "1"

# Redirection pour les URLs direct vers les fragments
[[redirects]]
  from = "/career/share/:id"
  to = "/career#:id"
  status = 302
  force = true

# Redirection pour l'URL career principale
[[redirects]]
  from = "/career"
  to = "/career/index.html"
  status = 200

# Redirection pour les identifiants career
[[redirects]]
  from = "/career/*"
  to = "/career/index.html"
  status = 200

# Redirection par défaut pour une Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200