[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/career/*"
  to = "/career/#:splat"
  status = 302
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200